### ISSUE TITLE
after upgrade to Android 8.1, Kore crashes when selecting a artist in the music list

### ISSUE THREAD

**Issue by lvdstam** [xbmc/Kore#492]
Recently I installed Android 8.1 on my Nexus 5X. Since then I cannot use the app anymore. I'm experiencing all kinds of crashes.

For instance when selecting Music from the side menu, I get the list of artists. Then when I tap on an artist, the app crashes. After installing and building the app from the sources I get the below stack trace:

12-16 12:29:32.701 18886-18886/org.xbmc.kore E/AndroidRuntime: FATAL EXCEPTION: main
                                                               Process: org.xbmc.kore, PID: 18886
                                                               java.lang.UnsupportedOperationException: removeView(View) is not supported in AdapterView
                                                                   at android.widget.AdapterView.removeView(AdapterView.java:531)
                                                                   at android.view.ViewOverlay$OverlayViewGroup.add(ViewOverlay.java:195)
                                                                   at android.view.ViewGroupOverlay.add(ViewGroupOverlay.java:72)
                                                                   at android.transition.TransitionUtils.createViewBitmap(TransitionUtils.java:170)
                                                                   at android.transition.TransitionUtils.copyViewImage(TransitionUtils.java:104)
                                                                   at android.transition.Visibility.onDisappear(Visibility.java:380)
                                                                   at android.transition.Visibility.createAnimator(Visibility.java:249)
                                                                   at android.transition.Transition.createAnimators(Transition.java:732)
                                                                   at android.transition.TransitionSet.createAnimators(TransitionSet.java:396)
                                                                   at android.transition.Transition.playTransition(Transition.java:1779)
                                                                   at android.transition.TransitionManager$MultiListener.onPreDraw(TransitionManager.java:315)
                                                                   at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:977)
                                                                   at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2349)
                                                                   at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1392)
                                                                   at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6752)
                                                                   at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
                                                                   at android.view.Choreographer.doCallbacks(Choreographer.java:723)
                                                                   at android.view.Choreographer.doFrame(Choreographer.java:658)
                                                                   at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
                                                                   at android.os.Handler.handleCallback(Handler.java:790)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                   at android.os.Looper.loop(Looper.java:164)
                                                                   at android.app.ActivityThread.main(ActivityThread.java:6494)
                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

Other crashes with different signatures happen when I first switch to the Albums tab and select an album there.

Please look into this...

**Comment by lvdstam** [comment]
I can confirm that this problem/behavior also exists when running the App on the Android 8.1 emulator

**Comment by SyncedSynapse** [comment]
I've also seen this happening on 8.1, though i haven't been able to take a look at it (i've seen an ANR, which should be the same reported on this issue).

Strangely there's no reports of it in the Play store yet...

**Comment by poisdeux** [comment]
From the log this seems to be an issue with the shared element transition. It might be something we're doing wrong, but I have a feeling this issue is on android's side.

**Comment by lvdstam** [comment]
Hi Martijn,

Can you explain a bit more about the shared element transition. Where it
sits and how it is used in the app... I will take a look, probably I won't
solve it, but I will have learned something :-)


On Dec 19, 2017 15:29, "Martijn Brekhof" <notifications@github.com> wrote:

From the log this seems to be an issue with the shared element transition.
It might be something we're doing wrong, but I have a feeling this issue is
on android's side.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/xbmc/Kore/issues/492#issuecomment-352770734>, or mute
the thread

**Comment by poisdeux** [comment]
After some research I get the feeling we were just lucky it worked. Shared element transitions between fragments was never really well documented. We got it working fairly well using a trial and error procedure. However, the [transitions framework](https://developer.android.com/training/transitions/overview.html#Transitions) never supported `AdapterView`, as it handles its childs different from other `ViewGroups`. With 8.1, google is trying to decrease memory usage and that is probably why it now does call `removeView`.

So as I understand this now, we could fix this in three ways:
1. Disable shared element transitions for 8.1 and higher.
2. We create a custom `GridView` implementing the missing method, which should do nothing. 
3. Refactor our code to use  [RecyclerView](https://developer.android.com/reference/android/support/v7/widget/RecyclerView.html) instead of `GridView`.

Option 3 is the real solution (IMO), but will take more time. So we could start with option 1 and afterwards fix it correctly.

Our shared element implementation is implemented in the [SharedElementTransition](https://github.com/xbmc/Kore/blob/master/app/src/main/java/org/xbmc/kore/utils/SharedElementTransition.java) class. Which is used by [`BaseMediaActivity`](https://github.com/xbmc/Kore/blob/master/app/src/main/java/org/xbmc/kore/ui/BaseMediaActivity.java) to set up the shared element transition for the fragments at lines [162](https://github.com/xbmc/Kore/blob/master/app/src/main/java/org/xbmc/kore/ui/BaseMediaActivity.java#L162) and [285](https://github.com/xbmc/Kore/blob/master/app/src/main/java/org/xbmc/kore/ui/BaseMediaActivity.java#L285).

Google documentation regarding shared element transition can be found [here](https://developer.android.com/training/material/animations.html#Transitions). Note, that it only talks about sharing elements between activities and not fragments. See this [tutorial](http://mikescamell.com/shared-element-transitions-part-2/) on how it works between fragments.

Would you like a go at fixing this?

**Comment by lvdstam** [comment]
Thanks for the information. I will attempt to fix it, but will first need
to familiarize myself with the codebase. Please be patient.

**Comment by SyncedSynapse** [comment]
@poisdeux 

You're refering to this limitation on the [link](https://developer.android.com/training/transitions/overview.html#Transitions) you provided, right:

> Classes that extend AdapterView, such as ListView, manage their child views in ways that are incompatible with the transitions framework. If you try to animate a view based on AdapterView, the device display may hang.

We should have moved to RecyclerViews a while ago... Anyway, if disabling animations for 8.1 is something straightforward we should do it, as this is affecting a lot of people (506 at the last count).

**Comment by poisdeux** [comment]
@SyncedSynapse indeed and indeed.

@lvdstam I'll apply the quick fix, so you can take your time for the real fix.
