### ISSUE TITLE
crash on startup after kodi upgrade

### ISSUE THREAD

**Issue by rigid** [xbmc/Kore#52]
I'm using Kore 1.2.1 from f-droid. After I upgraded kodi to 15.0-ALPHA2 Git:2c6d5a8, kore crashes on startup with:

```
I/Timeline( 2658): Timeline: Activity_launch_request id:org.xbmc.kore time:87036639
I/ActivityManager( 2290): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.xbmc.kore/.ui.RemoteActivity bnds=[190,902][360,1115]} from pid 2658
V/Zygote  (10640): Switching descriptor 32 to /dev/null
V/Zygote  (10640): Switching descriptor 9 to /dev/null
I/ActivityManager( 2290): Start proc org.xbmc.kore for activity org.xbmc.kore/.ui.RemoteActivity: pid=10640 uid=10172 gids={50172, 3003, 1028, 1015}
D/ActivityThread(10640): handleBindApplication:org.xbmc.kore
D/ActivityThread(10640): setTargetHeapUtilization:0.75
D/ActivityThread(10640): setTargetHeapMinFree:2097152
I/dalvikvm(10640): Could not find method android.view.ViewAnimationUtils.createCircularReveal, referenced from method org.xbmc.kore.utils.UIUtils.switchToRemoteWithAnimation
W/dalvikvm(10640): VFY: unable to resolve static method 7578: Landroid/view/ViewAnimationUtils;.createCircularReveal (Landroid/view/View;IIFF)Landroid/animation/Animator;
D/dalvikvm(10640): VFY: replacing opcode 0x71 at 0x001b
D/libEGL  (10640): loaded /system/lib/egl/libEGL_mali.so
D/libEGL  (10640): loaded /system/lib/egl/libGLESv1_CM_mali.so
D/libEGL  (10640): loaded /system/lib/egl/libGLESv2_mali.so
E/        (10640): Device driver API match
E/        (10640): Device driver API version: 23
E/        (10640): User space API version: 23 
E/        (10640): mali: REVISION=Linux-r3p2-01rel3 BUILD_DATE=Fri Mar 21 13:52:50 KST 2014 
D/OpenGLRenderer(10640): Enabling debug mode 0
I/HK/LatinKeyboardBaseView( 2572): closing org.pocketworkstation.pckeyboard.LatinKeyboardView{41dd5988 V.ED.... ......ID 0,0-720,320 #1020026 android:id/keyboardView}
I/ActivityManager( 2290): Displayed org.xbmc.kore/.ui.RemoteActivity: +725ms
I/Timeline( 2290): Timeline: Activity_windows_visible id: ActivityRecord{41fa4cd8 u0 org.xbmc.kore/.ui.RemoteActivity t165} time:87037463
I/Timeline(10640): Timeline: Activity_idle id: android.os.BinderProxy@421cae98 time:87037502
E/rsC++   ( 2658): RS Message thread exiting.
W/dalvikvm(10640): threadid=12: thread exiting with uncaught exception (group=0x41935ce0)
E/AndroidRuntime(10640): FATAL EXCEPTION: Thread-3441
E/AndroidRuntime(10640): Process: org.xbmc.kore, PID: 10640
E/AndroidRuntime(10640): java.lang.ClassCastException: com.fasterxml.jackson.databind.node.TextNode cannot be cast to com.fasterxml.jackson.databind.node.ArrayNode
E/AndroidRuntime(10640): 	at org.xbmc.kore.jsonrpc.type.VideoType$Cast.castListFromJsonNode(VideoType.java:60)
E/AndroidRuntime(10640): 	at org.xbmc.kore.jsonrpc.type.ListType$ItemBase.<init>(ListType.java:221)
E/AndroidRuntime(10640): 	at org.xbmc.kore.jsonrpc.type.ListType$ItemsAll.<init>(ListType.java:303)
E/AndroidRuntime(10640): 	at org.xbmc.kore.jsonrpc.method.Player$GetItem.resultFromJson(Player.java:88)
E/AndroidRuntime(10640): 	at org.xbmc.kore.jsonrpc.method.Player$GetItem.resultFromJson(Player.java:68)
E/AndroidRuntime(10640): 	at org.xbmc.kore.jsonrpc.HostConnection.handleTcpResponse(HostConnection.java:729)
E/AndroidRuntime(10640): 	at org.xbmc.kore.jsonrpc.HostConnection.access$400(HostConnection.java:49)
E/AndroidRuntime(10640): 	at org.xbmc.kore.jsonrpc.HostConnection$7.run(HostConnection.java:583)
E/AndroidRuntime(10640): 	at java.lang.Thread.run(Thread.java:841)
W/ActivityManager( 2290):   Force finishing activity org.xbmc.kore/.ui.RemoteActivity
E/        ( 2658): Device driver API match
E/        ( 2658): Device driver API version: 23
E/        ( 2658): User space API version: 23 
E/        ( 2658): mali: REVISION=Linux-r3p2-01rel3 BUILD_DATE=Fri Mar 21 13:52:50 KST 2014 
V/RenderScript( 2658): 0x609e14d0 Launching thread(s), CPUs 3
I/Timeline( 2658): Timeline: Activity_idle id: android.os.BinderProxy@41d90f68 time:87037934
I/Timeline( 2290): Timeline: Activity_windows_visible id: ActivityRecord{41d81f40 u0 com.teslacoilsw.launcher/com.android.launcher2.Launcher t1} time:87038343
```

**Comment by SyncedSynapse** [comment]
This should be fixed by d34d080adfca59182e5f350aeb7f994c93cdb6c5
Can you test it?

**Comment by rigid** [comment]
I can't compile Kore right now, I'm afraid. 
I could test an f-droid release or a custom .apk release.
(Additionally I found out, that the error only occurs when TV playback is active. Video, Music, etc. all work fine.)

**Comment by SyncedSynapse** [comment]
Join the beta program http://forum.kodi.tv/showthread.php?tid=221703 and check if the next release fixes this. I'm pretty certain it will. If it doesn't reopen this or create a new one.

**Comment by rigid** [comment]
works fine in 1.3.0. Thank you.
