### ISSUE TITLE
"Guide" in PVR causes crash

### ISSUE THREAD

**Issue by heeplr** [xbmc/Kore#745]
### Describe the bug
Here is a clear and concise description of what the problem is:

Selecting "Guide" in the PVR section causes crash.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

It's expected that the EPG is shown.

## Actual Behavior

Crash.

## Possible Fix

Don't use removeView() in an AdapterView?

### To Reproduce

1. Go to "PVR" section
2. From any channel, open the "..." context menu.
3. Select "Guide"

### Debuglog

The debuglog:
```
msg: java.lang.UnsupportedOperationException: removeView(View) is not supported in AdapterView
stacktrace: java.lang.UnsupportedOperationException: removeView(View) is not supported in AdapterView
	at android.widget.AdapterView.removeView(AdapterView.java:531)
	at android.view.ViewOverlay$OverlayViewGroup.add(ViewOverlay.java:195)
	at android.view.ViewGroupOverlay.add(ViewGroupOverlay.java:72)
	at android.transition.TransitionUtils.createViewBitmap(TransitionUtils.java:171)
	at android.transition.TransitionUtils.copyViewImage(TransitionUtils.java:103)
	at android.transition.Visibility.onDisappear(Visibility.java:383)
	at android.transition.Visibility.createAnimator(Visibility.java:252)
	at android.transition.Transition.createAnimators(Transition.java:732)
	at android.transition.TransitionSet.createAnimators(TransitionSet.java:396)
	at android.transition.Transition.playTransition(Transition.java:1779)
	at android.transition.TransitionManager$MultiListener.onPreDraw(TransitionManager.java:315)
	at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:977)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2489)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1481)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7393)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
	at android.view.Choreographer.doCallbacks(Choreographer.java:761)
	at android.view.Choreographer.doFrame(Choreographer.java:696)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6724)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

### Screenshots 
Here are some links or screenshots to help explain the problem:

No screenshot. The app is closed.

### Your Environment
Used Operating system:

 - Mobile device: SM-G930F (herolte)
 - Android version: 9
 - Kodi version and platform: Kodi 18.7 Git:20200608-nogitfound / gentoo
 - Kore version: 2.5.0

**Comment by anonimno1** [comment]
Hello,

I have the same problem with the Kore 2.5.0 from f-droid and LOS17.1 (Android 10).
Cheers and hope to get this fixed soon.
