### ISSUE TITLE
JSON persing exception when loading PVR recordings

### ISSUE THREAD

**Issue by Selaron** [xbmc/Kore#790]
When loading the PVR Recordings tab, I get following exception:

> D/PVRChannelsListFragment: Got channels
> D/HostConnection: Starting method execute. Method: PVR.GetRecordings on host: http://192.168.1.185:8080/jsonrpc
> D/HostConnection: Sending request via TCP: {"jsonrpc":"2.0","method":"PVR.GetRecordings","id":34,"params":{"properties":["title","plot","plotoutline","genre","playcount","resume","channel","starttime","endtime","runtime","lifetime","icon","art","streamurl","file","directory"]}}
> W/HostConnection: Got an exception while parsing JSON response.
>     com.fasterxml.jackson.core.JsonParseException: Invalid UTF-8 middle byte 0x67
>      at [Source: java.net.SocketInputStream@eeb2c0d; line: 1, column: 405016]
>         at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1487)
>         at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:518)
>         at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._reportInvalidOther(UTF8StreamJsonParser.java:3345)
>         at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._reportInvalidOther(UTF8StreamJsonParser.java:3352)
>         at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._decodeUtf8_2(UTF8StreamJsonParser.java:3126)
>         at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._finishString2(UTF8StreamJsonParser.java:2334)
>         at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._finishString(UTF8StreamJsonParser.java:2287)
>         at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.getText(UTF8StreamJsonParser.java:286)
>         at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:230)
>         at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeArray(JsonNodeDeserializer.java:267)
>         at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:227)
>         at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:224)
>         at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:62)
>         at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:14)
>         at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3534)
>         at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:1978)
>         at org.xbmc.kore.jsonrpc.HostConnection$8.run(HostConnection.java:771)
>         at java.lang.Thread.run(Thread.java:923)
> D/PVRRecordingsListFragm: Error getting recordings: com.fasterxml.jackson.core.JsonParseException: Invalid UTF-8 middle byte 0x67
>      at [Source: java.net.SocketInputStream@eeb2c0d; line: 1, column: 405016]
> D/CompatibilityChangeReporter: Compat change id reported: 147798919; UID 10155; state: DISABLED
> 

App version is either current F-Droid upstream and current master branch.
Kodi Version is 19 and 18.8
PCR Backend is VDR 2.4.1-4.1: amd64 on debian bullseye.
VNSI Server version is 1:1.8.0-3: amd64 on debian bullseye.

Before upgrading debian from buster to bullseye I've seen this issue sporadically, now it occures every time

**Comment by iwikus** [comment]
Same here
![kore-pvr](https://user-images.githubusercontent.com/30178330/126313872-3dd850de-602d-489a-a4d8-a469922622fe.jpg)
always have this exception. Could somebody please fix this?

**Comment by kambala-decapitator** [comment]
we saw similar errors in https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/164 which was confirmed to be a backend issue: https://tvheadend.org/issues/6003

you should check if raw output is a valid UTF-8 (e.g. with `curl`). If not, then most probably it's also a backend bug.

**Comment by iwikus** [comment]
Can you please provide URL for this json? I can upload it here, to confirm.

**Comment by SyncedSynapse** [comment]
Is this still relevant?

**Comment by iwikus** [comment]
I am unable to replicate on my side. If it was caused by some recording, it may be deleted.

**Comment by SyncedSynapse** [comment]
Closing for now, if it happens again in v3.0.0 reopen.
